#!/bin/bash

set -e
red=`tput setaf 1`
green=`tput setaf 2`

GIT_REPOSITORY="https://jenisakthi143:ADtsCHdMJBjDhb6syjc7@bitbucket.org/jenisakthi/samplepythonjeni.git"
BUILD_DIR="/deployment/"
REPOSITORY_NAME="samplepythonjeni/"
CURRENT_WORKING_DIR="/opt/tomcat/apache-tomcat-9.0.56/webapps"
BACKUP_DIRECTORY="/root/devops/"
WAR_FILE="ROOT.war"
BACKUP_WAR_FILE=$WAR_FILE"_"$( date +%F%H_%mm_%S)
ROOT_DIR="ROOT"
BACKUP_ROOT_DIR=$ROOT_DIR"_"$( date +%F%H_%mm_%S)
LATEST_DEPLOYMENT_FILE=$1

if [ $(id -u) -ne 0 ]; then
    echo "${red}you should be sudo to execute this script"
    exit 1
fi


if [ -z "$LATEST_DEPLOYMENT_FILE" ]
then
        echo "${red} argument passes is null"
        exit 1
fi

if [[ $LATEST_DEPLOYMENT_FILE != *.war ]]
then
        echo "${red} it is not a war file"
        exit 1
fi

echo  "${green}$LATEST_DEPLOYMENT_FILE"


if [ ! -d "$BUILD_DIR" ]; then
  mkdir $BUILD_DIR
  if [ ! -d "$BUILD_DIR$REPOSITORY_NAME" ]; then
        mkdir $BUILD_DIR$REPOSITORY_NAME
        cd $BUILD_DIR$REPOSITORY_NAME && /usr/bin/git clone $GIT_REPOSITORY 
  fi
fi

cd $BUILD_DIR$REPOSITORY_NAME && git pull origin master

if [ $? -ne 0 ]; then
    echo "${red}git pull is failed you have some local changes"
    exit 1
fi


if [ ! -f "$BUILD_DIR$REPOSITORY_NAME$LATEST_DEPLOYMENT_FILE" ]; then
        echo "${red}provided war file : $LATEST_DEPLOYMENT_FILE not found in the repository"
        exit 1
fi

/etc/init.d/tomcat stop

if [ $? -ne 0 ]; then
    echo "${red}Tomcat is failed to stop"
    exit 1
fi

echo "${green}tomcat successfully stopped"

if [ ! -d "$BACKUP_DIRECTORY" ]; then
        mkdir $BACKUP_DIRECTORY
fi

mv $CURRENT_WORKING_DIR/$WAR_FILE $BACKUP_DIRECTORY/$BACKUP_WAR_FILE

if [ $? -ne 0 ]; then
    echo "${red}Backup of root.war fails"
    exit 1
fi

echo "${green}backup of root.war file is successful"

mv $CURRENT_WORKING_DIR/$ROOT_DIR $BACKUP_DIRECTORY/$BACKUP_ROOT_DIR

if [ $? -ne 0 ]; then
    echo "${red}Backup of root fails"
     exit 1
fi

echo "${green}backup of root folder is succesfull"

cp $BUILD_DIR$REPOSITORY_NAME$LATEST_DEPLOYMENT_FILE $CURRENT_WORKING_DIR

if [ $? -ne 0 ]; then
    echo "${red}Deployment file not found in git repo"
    exit 1
fi

mv $CURRENT_WORKING_DIR/$LATEST_DEPLOYMENT_FILE $CURRENT_WORKING_DIR/$WAR_FILE

echo "${green}latest deployment file is moved into working dir"

/etc/init.d/tomcat start

if [ $? -ne 0 ]; then
    echo "Tomcat is failed to start"
    exit 1
fi

echo "${green}tomcat is started and deployment is successful"
